### ISSUE TITLE
[enhancement] Add connection status to admin

### ISSUE THREAD

**Issue by robotconscience** [Spacebrew/spacebrew#65] opened 2016-02-19 15:02 UTC
Some sort of visual representation of:  
* Are we connected to the server?
* What URL are we connected to?

**Comment by quinkennedy** [comment] 2016-02-19 17:13
duplicate of #31

**Comment by robotconscience** [comment] 2016-02-19 17:13
Ah geez. Sorry!

**Closed by quinkennedy** 2016-02-19 17:13 UTC
Labels: enhancement, high
